# Generated by Django 5.2.8 on 2025-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailers', '0002_emailburst_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailburst',
            name='sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
