# Generated by Django 4.2.15 on 2025-11-17 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailers', '0003_alter_emailburst_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailburst',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailburst',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailburst',
            name='recipients',
            field=models.ManyToManyField(related_name='received_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberDeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('not_found', 'Not Found'), ('connection_error', 'Connection Error'), ('other_error', 'Other Error')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_burst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailers.emailburst')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('member', 'email_burst')},
            },
        ),
    ]
