# Generated by Django 4.2.15 on 2025-11-17 15:16

from django.db import migrations
from django.contrib.auth import get_user_model
from emailers.models import Member, EmailBurst
from django.utils import timezone
from datetime import datetime, timedelta
import random

User = get_user_model()

def create_sample_data(apps, schema_editor):
    """Create sample data for the application"""
    # Create 2 staff users
    staff_data = [
        {
            'username': 'staff_john',
            'email': 'john.doe@staff.com',
            'first_name': 'John',
            'last_name': 'Doe',
            'password': 'password123'
        },
        {
            'username': 'staff_jane',
            'email': 'jane.smith@staff.com',
            'first_name': 'Jane',
            'last_name': 'Smith',
            'password': 'password123'
        }
    ]

    staff_users = []
    for staff_info in staff_data:
        staff = User(
            username=staff_info['username'],
            email=staff_info['email'],
            first_name=staff_info['first_name'],
            last_name=staff_info['last_name'],
            is_staff=True,
            is_active=True
        )
        staff.set_password(staff_info['password'])
        staff.save()
        staff_users.append(staff)

    # Create 10 dummy members
    member_data = [
        {'username': 'member1', 'email': 'member1@example.com', 'first_name': 'Alice', 'last_name': 'Johnson', 'middle_name': 'Marie'},
        {'username': 'member2', 'email': 'member2@example.com', 'first_name': 'Bob', 'last_name': 'Williams', 'middle_name': 'James'},
        {'username': 'member3', 'email': 'member3@example.com', 'first_name': 'Carol', 'last_name': 'Brown', 'middle_name': 'Ann'},
        {'username': 'member4', 'email': 'member4@example.com', 'first_name': 'David', 'last_name': 'Jones', 'middle_name': 'Robert'},
        {'username': 'member5', 'email': 'member5@example.com', 'first_name': 'Emma', 'last_name': 'Garcia', 'middle_name': 'Louise'},
        {'username': 'member6', 'email': 'member6@example.com', 'first_name': 'Frank', 'last_name': 'Miller', 'middle_name': 'Thomas'},
        {'username': 'member7', 'email': 'member7@example.com', 'first_name': 'Grace', 'last_name': 'Davis', 'middle_name': 'Elizabeth'},
        {'username': 'member8', 'email': 'member8@example.com', 'first_name': 'Henry', 'last_name': 'Rodriguez', 'middle_name': 'Michael'},
        {'username': 'member9', 'email': 'member9@example.com', 'first_name': 'Ivy', 'last_name': 'Martinez', 'middle_name': 'Rose'},
        {'username': 'member10', 'email': 'member10@example.com', 'first_name': 'Jack', 'last_name': 'Hernandez', 'middle_name': 'Lee'}
    ]

    members = []
    for member_info in member_data:
        member = Member(
            username=member_info['username'],
            email=member_info['email'],
            first_name=member_info['first_name'],
            last_name=member_info['last_name'],
            middle_name=member_info['middle_name'],
            is_active=True
        )
        member.set_password('password123')
        member.save()
        members.append(member)

    # Create 2 email bursts
    email_data = [
        {
            'subject': 'Welcome to Our Community!',
            'body': '''
            <h1>Welcome to Our Community!</h1>
            <p>Dear Member,</p>
            <p>We are excited to have you join our community. You'll find that we offer the best services and support to help you achieve your goals.</p>
            <p>Best regards,<br>The Team</p>
            ''',
            'sender': staff_users[0].email
        },
        {
            'subject': 'Monthly Newsletter - October 2024',
            'body': '''
            <h1>Monthly Newsletter - October 2024</h1>
            <p>Dear Members,</p>
            <p>Here's what's happening this month:</p>
            <ul>
                <li>New features added to our platform</li>
                <li>Upcoming events and webinars</li>
                <li>Tips and best practices</li>
            </ul>
            <p>Stay tuned for more updates!</p>
            <p>Best regards,<br>The Team</p>
            ''',
            'sender': staff_users[1].email
        }
    ]

    for i, email_info in enumerate(email_data):
        email_burst = EmailBurst(
            subject=email_info['subject'],
            body=email_info['body'],
            sender=email_info['sender']
        )
        email_burst.save()
        # Add some members as recipients (first email gets first 5 members, second gets last 5)
        start_idx = i * 5
        end_idx = start_idx + 5
        selected_members = members[start_idx:end_idx]
        for member in selected_members:
            email_burst.recipients.add(member)

def reverse_sample_data(apps, schema_editor):
    """Reverse the sample data creation"""
    # Delete the created data
    Member = apps.get_model('emailers', 'Member')
    EmailBurst = apps.get_model('emailers', 'EmailBurst')
    User = apps.get_model('auth', 'User')

    # Remove created members
    Member.objects.filter(username__in=[
        'member1', 'member2', 'member3', 'member4', 'member5',
        'member6', 'member7', 'member8', 'member9', 'member10'
    ]).delete()

    # Remove created email bursts
    EmailBurst.objects.filter(subject__in=[
        'Welcome to Our Community!',
        'Monthly Newsletter - October 2024'
    ]).delete()

    # Remove created staff users
    User.objects.filter(username__in=[
        'staff_john', 'staff_jane'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emailers', '0004_emailburst_is_sent_emailburst_sent_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_sample_data, reverse_sample_data),
    ]
