# Generated by Django 4.2.15 on 2025-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailers', '0005_auto_20251117_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailburst',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/'),
        ),
    ]
